version: '2'
services:
    itgm-app:
        image: itgm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://itgm-postgresql:5432/itgm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    itgm-postgresql:
        extends:
            file: postgresql.yml
            service: itgm-postgresql
